package flashcard;

import java.util.LinkedHashMap;
import java.util.Map;

public class Lang {
	Map<String, String> map;

	public void initLanguageMap() {
		map = new LinkedHashMap<String, String>();
		map.put("math", "Math / Symbols");
		map.put("chem", "Chemistry");
		map.put("af", "Afrikaans");
		map.put("ak", "Akan");
		map.put("akk", "Akkadian");
		map.put("sq", "Albanian");
		map.put("ase", "American Sign Language");
		map.put("am", "Amharic");
		map.put("ar", "Arabic");
		map.put("hy", "Armenian");
		map.put("az", "Azerbaijani");
		map.put("eu", "Basque");
		map.put("be", "Belarusian");
		map.put("bn", "Bengali");
		map.put("bh", "Bihari");
		map.put("bs", "Bosnian");
		map.put("bg", "Bulgarian");
		map.put("br", "Breton");
		map.put("my", "Burmese");
		map.put("ca", "Catalan");
		map.put("ceb", "Cebuano");
		map.put("ch", "Chamorro");
		map.put("chr", "Cherokee");
		map.put("zh-CN", "Chinese (Simplified)");
		map.put("zh-pi", "Chinese (Pinyin)");
		map.put("zh-TW", "Chinese (Traditional)");
		map.put("co", "Corsican");
		map.put("cho", "Choctaw");
		map.put("cop", "Coptic");
		map.put("hr", "Croatian");
		map.put("cs", "Czech");
		map.put("da", "Danish");
		map.put("den", "Dene");
		map.put("dv", "Dhivehi");
		map.put("nl", "Dutch");
		map.put("en", "English");
		map.put("eo", "Esperanto");
		map.put("et", "Estonian");
		map.put("fo", "Faroese");
		map.put("fi", "Finnish");
		map.put("dyo", "Fonyi Jola");
		map.put("fr", "French");
		map.put("ff", "Fula");
		map.put("gd", "Gaelic");
		map.put("gl", "Galician");
		map.put("ka", "Georgian");
		map.put("de", "German");
		map.put("el", "Greek");
		map.put("gn", "Guarani");
		map.put("gu", "Gujarati");
		map.put("hai", "Haida");
		map.put("ht", "Haitian");
		map.put("ha", "Hausa");
		map.put("haw", "Hawaiian");
		map.put("iw", "Hebrew");
		map.put("hi", "Hindi");
		map.put("hu", "Hungarian");
		map.put("is", "Icelandic");
		map.put("ig", "Igbo");
		map.put("id", "Indonesian");
		map.put("iu", "Inuktitut");
		map.put("ga", "Irish");
		map.put("it", "Italian");
		map.put("ja", "Japanese");
		map.put("ja-ro", "Japanese (Romaji)");
		map.put("ja-ka", "Japanese (Kana)");
		map.put("jv", "Javanese");
		map.put("kg", "KiKongo");
		map.put("kin", "Kinyarwanda");
		map.put("kn", "Kannada");
		map.put("kk", "Kazakh");
		map.put("km", "Khmer");
		map.put("ko", "Korean");
		map.put("ksw", "Sgaw Karen");
		map.put("ku", "Kurdish");
		map.put("ky", "Kyrgyz");
		map.put("lkt", "Lakota");
		map.put("lo", "Lao");
		map.put("la", "Latin");
		map.put("lv", "Latvian");
		map.put("unm", "Lenape");
		map.put("ln", "Lingala");
		map.put("lt", "Lithuanian");
		map.put("lua", "Luba-Kasai");
		map.put("lb", "Luxembourgish");
		map.put("mk", "Macedonian");
		map.put("ms", "Malay");
		map.put("ml", "Malayalam");
		map.put("mt", "Maltese");
		map.put("mi", "Maori");
		map.put("rar", "Maori (Cook Islands)");
		map.put("mr", "Marathi");
		map.put("mh", "Marshallese");
		map.put("mn", "Mongolian");
		map.put("nah", "Nahuatl");
		map.put("ne", "Nepali");
		map.put("no", "Norwegian");
		map.put("oc", "Occitan");
		map.put("or", "Oriya");
		map.put("om", "Oromo");
		map.put("oj", "Ojibwe");
		map.put("pi", "Pāli");
		map.put("ps", "Pashto");
		map.put("fa", "Persian");
		map.put("fil", "Filipino");
		map.put("pl", "Polish");
		map.put("pt", "Portuguese");
		map.put("pa", "Punjabi");
		map.put("qu", "Quechua");
		map.put("ro", "Romanian");
		map.put("rm", "Romansh");
		map.put("ru", "Russian");
		map.put("sa", "Sanskrit");
		map.put("sr", "Serbian");
		map.put("sd", "Sindhi");
		map.put("si", "Sinhalese");
		map.put("sk", "Slovak");
		map.put("sl", "Slovenian");
		map.put("es", "Spanish");
		map.put("su", "Sundanese");
		map.put("sw", "Swahili");
		map.put("sv", "Swedish");
		map.put("tl", "Tagalog");
		map.put("tg", "Tajik");
		map.put("ta", "Tamil");
		map.put("tt", "Tatar");
		map.put("te", "Telugu");
		map.put("th", "Thai");
		map.put("bo", "Tibetan");
		map.put("ti", "Tigrinya");
		map.put("to", "Tonga");
		map.put("ood", "Tohono O'odham");
		map.put("tr", "Turkish");
		map.put("tyv", "Tuvan");
		map.put("uk", "Ukrainian");
		map.put("ur", "Urdu");
		map.put("uz", "Uzbek");
		map.put("ug", "Uighur");
		map.put("vi", "Vietnamese");
		map.put("cy", "Welsh");
		map.put("fy", "Western Frisian");
		map.put("wo", "Wolof");
		map.put("xh", "Xhosa");
		map.put("yi", "Yiddish");
		map.put("yo", "Yoruba");
		map.put("zu", "Zulu");
		map.put("photo", "Photos");
	}

	public String codeToLanguage(String code) {
		return map.get(code);
	}
}
